#!/usr/bin/env zsh

clear

echo -e "$UNDERLINE$GREEN TaskWarrior $NONE"
echo -e "$CYAN Project.s\033[0m"
echo -e "$WHITE            :: [yasdb] Work on database tutorial::db_tutorial. # \033[0m"
echo -e "$WHITE            :: [rdnss] Work on dns server tutorial::dnsguide. #\033[0m"
echo -e "$WHITE            :: [RUST] Work on Rust Language. #\033[0m"
echo -e "$CYAN Concepts\033[0m"
echo -e "$WHITE            :: [ALGORITHMS] Work on data Structure. # \033[0m"
echo -e "$WHITE            :: [NETWORKING] Work on Networking subject. #\033[0m"
echo -e "$WHITE            :: [OPERATING SYSTEM] Work on Operating System subject. #\033[0m"
echo -e "$WHITE            :: [COMPILERS] Work on Compiler subject. #\033[0m"
echo -e "$UNDERLINE$GREEN TimeWarrior $NONE"
echo -e "$CYAN READING\033[0m"
echo -e "$WHITE            :: f reading book fiction\033[0m"
echo -e "$WHITE            :: nf reading book nonfiction\033[0m"
echo -e "$WHITE            :: ra reading articles\033[0m"
echo -e "$WHITE            :: wbw waitbutwhy reading articles\033[0m"
echo -e "$WHITE            :: tk theken reading articles\033[0m"
echo -e "$WHITE            :: rn reading notes\033[0m"
echo -e "$WHITE            :: tmc themorningcontext reading articles\033[0m"
echo -e "$WHITE            :: th thehindu reading articles\033[0m"
echo -e "$WHITE            :: fs farnam street reading articles\033[0m"
echo -e "$CYAN WELLNESS\033[0m"
echo -e "$WHITE            :: n netflix entertainment wellness\033[0m"
echo -e "$WHITE            :: h hotstar entertainment wellness\033[0m"
echo -e "$WHITE            :: porn pleasure entertainment wellness\033[0m"
echo -e "$WHITE            :: y youtube entertainment wellness\033[0m"
echo -e "$WHITE            :: video entertainment wellness\033[0m"
echo -e "$CYAN PROJECTS\033[0m"
echo -e "$WHITE            :: yd yasdb c project database\033[0m"
echo -e "$WHITE            :: rd rdnss rust project networking\033[0m"
echo -e "$WHITE            :: sk sakgames rust project games\033[0m"
echo -e "$WHITE            :: rk rkosh rust project password-manager\033[0m"
echo -e "$WHITE            :: sh yassh rust project shell\033[0m"
echo -e "$WHITE            :: ub porting halium ubports ubuntu-touch project os\033[0m"
echo -e "$WHITE            :: ss shell-script scripts project"
echo -e "$CYAN CONCEPTS\033[0m"
echo -e "$WHITE            :: dsa algorithms concepts studying computer science\033[0m"
echo -e "$WHITE            :: nw networking concepts studying computer science\033[0m"
echo -e "$WHITE            :: ci compilers interpreters concepts studying computer science\033[0m"
echo -e "$WHITE            :: os operating system concepts studying computer science\033[0m"
echo -e "$WHITE            :: wde udemy concepts studying web development\033[0m"
echo -e "$CYAN METAWORK\033[0m"
echo -e "$WHITE            :: tw timewarrior metawork\033[0m"
echo -e "$WHITE            :: ta taskwarrior metawork\033[0m"
echo -e "$WHITE            :: carrerissuelist cil metawork\033[0m"
echo -e "$WHITE            :: kb knowledge base trilium metawork\033[0m"
echo -e "$CYAN ESSENTIALS\033[0m"
echo -e "$WHITE            :: l lunch eating food essentials\033[0m"
echo -e "$WHITE            :: di dinner eating food essentials\033[0m"
echo -e "$WHITE            :: getting fresh ready bathing brushing no.2 essentials\033[0m"
echo -e "$WHITE            :: sl sleeping essentials\033[0m"
echo -e "$WHITE            :: ps pestle spices chores essentials\033[0m"
echo -e "$WHITE            :: kd kneading dough chores essentials\033[0m"
echo -e "$WHITE            :: bf brooming floor chores essentials\033[0m"
echo -e "$WHITE            :: ma massage chores essentials\033[0m"
echo -e "$WHITE            :: po pooja aarti chores essentials\033[0m"
echo -e "$WHITE            :: ic ironing clothes essentials chores\033[0m"
echo -e "$WHITE            :: wd washing dishes essentials chores\033[0m"
echo -e "$WHITE            :: cv cutting vegetables essentials chores\033[0m"
echo -e "$WHITE            :: cf cooking food essentials chores\033[0m"
echo -e "$CYAN MISC\033[0m"
echo -e "$WHITE            :: misc\033[0m"
